name: Upstream Sync # 工作流名称 / Workflow name

permissions:
  contents: write # 允许写入内容 / Allow write access to contents

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次 / Run once every day
  workflow_dispatch: # 允许手动触发工作流 / Allow manual triggering of the workflow

jobs:
  sync_latest_from_upstream: # 作业名称 / Job name
    name: Sync latest commits from upstream repo # 作业描述 / Job description
    runs-on: ubuntu-latest # 运行环境 / Run environment
    if: ${{ github.event.repository.fork }} # 仅在 fork 的仓库中运行 / Only run in forked repositories

    steps:
      # Step 1: run a standard checkout action
      - name: Checkout target repo # 步骤名称 / Step name
        uses: actions/checkout@main # 使用 checkout action / Use checkout action

      # Step 2: run the sync action
      - name: Sync upstream changes # 步骤名称 / Step name
        id: sync # 步骤 ID / Step ID
        uses: aormsby/Fork-Sync-With-Upstream-action@main # 使用同步上游的 action / Use action to sync with upstream
        with:
          upstream_sync_repo: mcMMO-Dev/mcMMO # 上游仓库地址 / Upstream repository address
          upstream_sync_branch: master # 上游分支名称 / Upstream branch name
          target_sync_branch: master # 目标分支名称 / Target branch name
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 自动生成的 GitHub 令牌，无需设置 / Automatically generated GitHub token, no need to set

          # 设置 test_mode 为 true 以运行测试而不是实际操作!! / Set test_mode to true to run tests instead of the actual action!!
          test_mode: false # 设置为 false 以执行真正的同步 / Set to false to perform the actual sync

      - name: Sync check # 步骤名称 / Step name
        if: failure() # 如果上一步失败，则执行此步骤 / Run this step if the previous step failed
        run: |
          echo "::error::由于权限不足，导致同步失败（这是预期的行为），请前往仓库首页手动执行[Sync fork]。"  # 打印错误信息（中文）/ Print error message (Chinese)
          echo "::error::Due to insufficient permissions, synchronization failed (as expected). Please go to the repository homepage and manually perform [Sync fork]."  # 打印错误信息（英文）/ Print error message (English)
          exit 1  # 退出状态码为 1，表示失败 / Exit with status code 1 to indicate failure
